Hammlet.Config.SceneSelectorConfig:
  TargetEntityId: "light.kitchen"
  EventIdPrefix: "event.alive_remote_scene_"
  BrightnessPct: 25
  Buttons:
    - Button1:
        Action: Brighten
        Type: KeyPressed
        EventIndex: "001"
        On:
          BrightnessStepPct: 25
    - Button2:
        Action: Darken
        Type: KeyPressed
        EventIndex: "002"
        On:
          BrightnessStepPct: 25.0
    - Button3:
        Action: ToggleWarm
        Type: KeyPressed
        EventIndex: "003"
    - Button4:
        Action: Toggle
        Type: KeyPressed
        EventIndex: "004"
