//------------------------------------------------------------------------------
// <auto-generated>
// Generated using NetDaemon CodeGenerator nd-codegen v24.50.0.0
//   At: 2024-12-14T14:51:18.4672061-08:00
//
// *** Make sure the version of the codegen tool and your nugets NetDaemon.* have the same version.***
// You can use following command to keep it up to date with the latest version:
//   dotnet tool update NetDaemon.HassModel.CodeGen
//
// To update this file with latest entities run this command in your project directory:
//   dotnet tool run nd-codegen
//
// In the template projects we provided a convenience powershell script that will update
// the codegen and nugets to latest versions update_all_dependencies.ps1.
//
// For more information: https://netdaemon.xyz/docs/user/hass_model/hass_model_codegen
// For more information about NetDaemon: https://netdaemon.xyz/
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json;
using System.Text.Json.Serialization;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using NetDaemon.HassModel.Entities.Core;

namespace Hammlet.NetDaemon.Models;
public partial class AutomationEntities
{
    private readonly IHaContext _haContext;
    public AutomationEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all automation entities currently registered (at runtime) in Home Assistant as AutomationEntity</summary>
    public IEnumerable<AutomationEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("automation.")).Select(e => new AutomationEntity(e));
    ///<summary>Turn Off</summary>
    public AutomationEntity Automation11 => new(_haContext, "automation.automation_11");
    ///<summary>Pants Emergency: 04 - Skip 2 if emergency times out</summary>
    public AutomationEntity Automation5 => new(_haContext, "automation.automation_5");
    ///<summary>Bedroom: Dimmer</summary>
    public AutomationEntity BedroomDimmer => new(_haContext, "automation.bedroom_dimmer");
    ///<summary>ChangeSoundMode</summary>
    public AutomationEntity Changesoundmode => new(_haContext, "automation.changesoundmode");
    ///<summary>lighting mode: Bright</summary>
    public AutomationEntity LightingModeBright => new(_haContext, "automation.lighting_mode_bright");
    ///<summary>lighting mode: Evenink</summary>
    public AutomationEntity LightingModeEvenink => new(_haContext, "automation.lighting_mode_evenink");
    ///<summary>lighting mode: Night</summary>
    public AutomationEntity LightingModeNight => new(_haContext, "automation.lighting_mode_night");
    ///<summary>lighting mode: Off</summary>
    public AutomationEntity LightingModeOff => new(_haContext, "automation.lighting_mode_off");
    ///<summary>lighting: Turn off at 2am</summary>
    public AutomationEntity LightingTurnOffAt2am => new(_haContext, "automation.lighting_turn_off_at_2am");
    ///<summary>Lights Dimmer</summary>
    public AutomationEntity LightsDimmer => new(_haContext, "automation.lights_dimmer");
    ///<summary>Pants Emergency: 05 - Return to normal when emgency over</summary>
    public AutomationEntity PantsEmergency05ReturnToNormalWhenEmgencyOver => new(_haContext, "automation.pants_emergency_05_return_to_normal_when_emgency_over");
    ///<summary>Pants Emergency: 03 - Cancel Timer when big button pressed</summary>
    public AutomationEntity PantsEmergencyCancelTimerWhenBigButtonPressed => new(_haContext, "automation.pants_emergency_cancel_timer_when_big_button_pressed");
    ///<summary>Pants Emergency: 04 - Play Next track (booty) if cancelled</summary>
    public AutomationEntity PantsEmergencyPlayNextTrackWhenResolved => new(_haContext, "automation.pants_emergency_play_next_track_when_resolved");
    ///<summary>Pants Emergency: 02 - Toggle Controller Switch </summary>
    public AutomationEntity PantsEmergencyToggleControllerSwitch => new(_haContext, "automation.pants_emergency_toggle_controller_switch");
    ///<summary>Party Lights</summary>
    public AutomationEntity PartyLights => new(_haContext, "automation.party_lights");
    ///<summary>Pause spotify when pants off</summary>
    public AutomationEntity PauseSpotifyWhenPantsOff => new(_haContext, "automation.pause_spotify_when_pants_off");
    ///<summary>Play Call To Action</summary>
    public AutomationEntity PlayCallToAction => new(_haContext, "automation.play_call_to_action");
    ///<summary>Play Mission Aborted</summary>
    public AutomationEntity PlayMissionAborted => new(_haContext, "automation.play_mission_aborted");
    ///<summary>Play Mission Aborted</summary>
    public AutomationEntity PlayMissionAborted2 => new(_haContext, "automation.play_mission_aborted_2");
    ///<summary>Play Success</summary>
    public AutomationEntity PlaySuccess => new(_haContext, "automation.play_success");
    ///<summary>Projector: Ping</summary>
    public AutomationEntity ProjectorPing => new(_haContext, "automation.projector_ping");
    ///<summary>Return to playlist</summary>
    public AutomationEntity ReturnToPlaylist => new(_haContext, "automation.return_to_playlist");
    ///<summary>Pants Emergency: 01 - Start when call to action is played</summary>
    public AutomationEntity StartEmergencyWhenMikaelaPlaysDanceYrselfClean => new(_haContext, "automation.start_emergency_when_mikaela_plays_dance_yrself_clean");
    ///<summary>Pants Emergency: 02 - Set Start Scene</summary>
    public AutomationEntity StartPantsEmergencyOnToggle => new(_haContext, "automation.start_pants_emergency_on_toggle");
    ///<summary>Turn off when over</summary>
    public AutomationEntity TurnOffWhenOver => new(_haContext, "automation.turn_off_when_over");
    ///<summary>Turn on evenink near sunset</summary>
    public AutomationEntity TurnOnEveninkNearSunset => new(_haContext, "automation.turn_on_evenink_near_sunset");
    ///<summary>Turn On Living Room TV with WakeOnLan</summary>
    public AutomationEntity TurnOnLivingRoomTvWithWakeonlan => new(_haContext, "automation.turn_on_living_room_tv_with_wakeonlan");
    ///<summary>Turn On Living Room TV with WakeOnLan</summary>
    public AutomationEntity TurnOnLivingRoomTvWithWakeonlan2 => new(_haContext, "automation.turn_on_living_room_tv_with_wakeonlan_2");
    ///<summary>Turn On speakers when things come online</summary>
    public AutomationEntity TurnOnSpeakersWhenThingsComeOnline => new(_haContext, "automation.turn_on_speakers_when_things_come_online");
}