//------------------------------------------------------------------------------
// <auto-generated>
// Generated using NetDaemon CodeGenerator nd-codegen v24.50.0.0
//   At: 2024-12-14T14:51:18.4716047-08:00
//
// *** Make sure the version of the codegen tool and your nugets NetDaemon.* have the same version.***
// You can use following command to keep it up to date with the latest version:
//   dotnet tool update NetDaemon.HassModel.CodeGen
//
// To update this file with latest entities run this command in your project directory:
//   dotnet tool run nd-codegen
//
// In the template projects we provided a convenience powershell script that will update
// the codegen and nugets to latest versions update_all_dependencies.ps1.
//
// For more information: https://netdaemon.xyz/docs/user/hass_model/hass_model_codegen
// For more information about NetDaemon: https://netdaemon.xyz/
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json;
using System.Text.Json.Serialization;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using NetDaemon.HassModel.Entities.Core;

namespace Hammlet.NetDaemon.Models;
public partial class ButtonEntities
{
    private readonly IHaContext _haContext;
    public ButtonEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all button entities currently registered (at runtime) in Home Assistant as ButtonEntity</summary>
    public IEnumerable<ButtonEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("button.")).Select(e => new ButtonEntity(e));
    ///<summary>Google Assistant Synchronize devices</summary>
    public ButtonEntity GoogleAssistantSynchronizeDevices => new(_haContext, "button.google_assistant_synchronize_devices");
    ///<summary>LG webOS TV EA88 Identify</summary>
    public ButtonEntity LgWebosTvEa88Identify => new(_haContext, "button.lg_webos_tv_ea88_identify");
    ///<summary>S2 Remote Control Switch Ping</summary>
    public ButtonEntity Node2Ping => new(_haContext, "button.node_2_ping");
    ///<summary>S2 Remote Control Switch Identify</summary>
    public ButtonEntity S2RemoteControlSwitchIdentify => new(_haContext, "button.s2_remote_control_switch_identify");
    ///<summary>Smart RGBTW Bulb Identify</summary>
    public ButtonEntity SmartRgbtwBulbIdentify => new(_haContext, "button.smart_rgbtw_bulb_identify");
    ///<summary>Smart RGBTW Bulb Identify</summary>
    public ButtonEntity SmartRgbtwBulbIdentify2 => new(_haContext, "button.smart_rgbtw_bulb_identify_2");
    ///<summary>Smart Wi-Fi Lamp Dimmer Identify</summary>
    public ButtonEntity SmartWiFiLampDimmerIdentify => new(_haContext, "button.smart_wi_fi_lamp_dimmer_identify");
    ///<summary>Smart Wi-Fi Lamp Dimmer Identify</summary>
    public ButtonEntity SmartWiFiLampDimmerIdentify2 => new(_haContext, "button.smart_wi_fi_lamp_dimmer_identify_2");
}