//------------------------------------------------------------------------------
// <auto-generated>
// Generated using NetDaemon CodeGenerator nd-codegen v24.50.0.0
//   At: 2024-12-14T14:51:18.4808893-08:00
//
// *** Make sure the version of the codegen tool and your nugets NetDaemon.* have the same version.***
// You can use following command to keep it up to date with the latest version:
//   dotnet tool update NetDaemon.HassModel.CodeGen
//
// To update this file with latest entities run this command in your project directory:
//   dotnet tool run nd-codegen
//
// In the template projects we provided a convenience powershell script that will update
// the codegen and nugets to latest versions update_all_dependencies.ps1.
//
// For more information: https://netdaemon.xyz/docs/user/hass_model/hass_model_codegen
// For more information about NetDaemon: https://netdaemon.xyz/
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json;
using System.Text.Json.Serialization;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using NetDaemon.HassModel.Entities.Core;

namespace Hammlet.NetDaemon.Models;
public partial class InputBooleanEntities
{
    private readonly IHaContext _haContext;
    public InputBooleanEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all input_boolean entities currently registered (at runtime) in Home Assistant as InputBooleanEntity</summary>
    public IEnumerable<InputBooleanEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("input_boolean.")).Select(e => new InputBooleanEntity(e));
    ///<summary>controller_flash</summary>
    public InputBooleanEntity ControllerFlash => new(_haContext, "input_boolean.controller_flash");
    ///<summary>dev_netdaemon_app_model_hello_yaml_app</summary>
    public InputBooleanEntity DevNetdaemonAppModelHelloYamlApp => new(_haContext, "input_boolean.dev_netdaemon_app_model_hello_yaml_app");
    ///<summary>dev_netdaemon_extensions_scheduling_scheduling_app</summary>
    public InputBooleanEntity DevNetdaemonExtensionsSchedulingSchedulingApp => new(_haContext, "input_boolean.dev_netdaemon_extensions_scheduling_scheduling_app");
    ///<summary>dev_netdaemon_hass_model_hello_world_app</summary>
    public InputBooleanEntity DevNetdaemonHassModelHelloWorldApp => new(_haContext, "input_boolean.dev_netdaemon_hass_model_hello_world_app");
    ///<summary>dev_netdaemon_hass_model_light_on_movement</summary>
    public InputBooleanEntity DevNetdaemonHassModelLightOnMovement => new(_haContext, "input_boolean.dev_netdaemon_hass_model_light_on_movement");
    ///<summary>dev_netdaemon_hass_model_scene_button_handler</summary>
    public InputBooleanEntity DevNetdaemonHassModelSceneButtonHandler => new(_haContext, "input_boolean.dev_netdaemon_hass_model_scene_button_handler");
    ///<summary>pants_emergency</summary>
    public InputBooleanEntity PantsEmergency => new(_haContext, "input_boolean.pants_emergency");
    ///<summary>party-mode</summary>
    public InputBooleanEntity PartyMode => new(_haContext, "input_boolean.party_mode");
}