//------------------------------------------------------------------------------
// <auto-generated>
// Generated using NetDaemon CodeGenerator nd-codegen v24.50.0.0
//   At: 2024-12-14T14:51:18.4615390-08:00
//
// *** Make sure the version of the codegen tool and your nugets NetDaemon.* have the same version.***
// You can use following command to keep it up to date with the latest version:
//   dotnet tool update NetDaemon.HassModel.CodeGen
//
// To update this file with latest entities run this command in your project directory:
//   dotnet tool run nd-codegen
//
// In the template projects we provided a convenience powershell script that will update
// the codegen and nugets to latest versions update_all_dependencies.ps1.
//
// For more information: https://netdaemon.xyz/docs/user/hass_model/hass_model_codegen
// For more information about NetDaemon: https://netdaemon.xyz/
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json;
using System.Text.Json.Serialization;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using NetDaemon.HassModel.Entities.Core;

namespace Hammlet.NetDaemon.Models;
public partial class LightEntities
{
    private readonly IHaContext _haContext;
    public LightEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all light entities currently registered (at runtime) in Home Assistant as LightEntity</summary>
    public IEnumerable<LightEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("light.")).Select(e => new LightEntity(e));
    ///<summary>Bedroom Fan Light</summary>
    public LightEntity BedroomFanLight => new(_haContext, "light.bedroom_fan_light");
    ///<summary>ESP8266 Demo LED 1 ESP8266 Demo LED 1</summary>
    public LightEntity Demoled1Esp8266DemoLed1 => new(_haContext, "light.demoled1_esp8266_demo_led_1");
    ///<summary>Bathroom</summary>
    public LightEntity HammletBathroom => new(_haContext, "light.hammlet_bathroom");
    ///<summary>Hammlet Bathroom</summary>
    public LightEntity HammletBathroom3 => new(_haContext, "light.hammlet_bathroom_3");
    ///<summary>Laser Lamp</summary>
    public LightEntity HammletExtra => new(_haContext, "light.hammlet_extra");
    ///<summary>Hammlet Pantry</summary>
    public LightEntity HammletPantry => new(_haContext, "light.hammlet_pantry");
    ///<summary>Hammlet Pantry</summary>
    public LightEntity HammletPantryOld => new(_haContext, "light.hammlet_pantry_old");
    ///<summary>Kitchen</summary>
    public LightEntity KitchenCeiling => new(_haContext, "light.kitchen_ceiling");
    ///<summary>Kitchen Light</summary>
    public LightEntity KitchenLight => new(_haContext, "light.kitchen_light");
    ///<summary>Alive</summary>
    public LightEntity Living => new(_haContext, "light.living");
    ///<summary>Hammlet Living Fan Light</summary>
    public LightEntity LivingFan => new(_haContext, "light.living_fan");
    ///<summary>Living Fan</summary>
    public LightEntity LivingFan2 => new(_haContext, "light.living_fan_2");
    ///<summary>Plant Lamp</summary>
    public LightEntity PlantLamp => new(_haContext, "light.plant_lamp");
    public LightEntity SmartWiFiLampDimmer => new(_haContext, "light.smart_wi_fi_lamp_dimmer");
    ///<summary>Smart Wi-Fi Lamp Dimmer</summary>
    public LightEntity SmartWiFiLampDimmerLight => new(_haContext, "light.smart_wi_fi_lamp_dimmer_light");
    ///<summary>Spamheart 2 Spamheart 2</summary>
    public LightEntity Spamheart2Spamheart2 => new(_haContext, "light.spamheart_2_spamheart_2");
    ///<summary>Spamheart Vein Spamheart Vein</summary>
    public LightEntity Spamheart4SpamheartVein => new(_haContext, "light.spamheart_4_spamheart_vein");
    ///<summary>Stripper Light</summary>
    public LightEntity StripperLight => new(_haContext, "light.stripper_light");
    ///<summary>Succulent Lamp</summary>
    public LightEntity SucculentLamp => new(_haContext, "light.succulent_lamp");
    ///<summary>Tentacle Lamp</summary>
    public LightEntity TentacleLamp => new(_haContext, "light.tentacle_lamp");
    ///<summary>Tentacle Lamp 2</summary>
    public LightEntity TentacleLamp2 => new(_haContext, "light.tentacle_lamp_2");
    public LightEntity YeelightColorb0x1b32258a => new(_haContext, "light.yeelight_colorb_0x1b32258a");
}