//------------------------------------------------------------------------------
// <auto-generated>
// Generated using NetDaemon CodeGenerator nd-codegen v24.50.0.0
//   At: 2024-12-14T14:51:18.4879200-08:00
//
// *** Make sure the version of the codegen tool and your nugets NetDaemon.* have the same version.***
// You can use following command to keep it up to date with the latest version:
//   dotnet tool update NetDaemon.HassModel.CodeGen
//
// To update this file with latest entities run this command in your project directory:
//   dotnet tool run nd-codegen
//
// In the template projects we provided a convenience powershell script that will update
// the codegen and nugets to latest versions update_all_dependencies.ps1.
//
// For more information: https://netdaemon.xyz/docs/user/hass_model/hass_model_codegen
// For more information about NetDaemon: https://netdaemon.xyz/
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json;
using System.Text.Json.Serialization;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using NetDaemon.HassModel.Entities.Core;

namespace Hammlet.NetDaemon.Models;
public partial class NumberEntities
{
    private readonly IHaContext _haContext;
    public NumberEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all number entities currently registered (at runtime) in Home Assistant as NumberEntity</summary>
    public IEnumerable<NumberEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("number.")).Select(e => new NumberEntity(e));
    ///<summary>Finger Robot 2 Down delay</summary>
    public NumberEntity FingerRobot2DownDelay => new(_haContext, "number.finger_robot_2_down_delay");
    ///<summary>Finger Robot 2 Move down</summary>
    public NumberEntity FingerRobot2MoveDown => new(_haContext, "number.finger_robot_2_move_down");
    ///<summary>Finger Robot 2 Move up</summary>
    public NumberEntity FingerRobot2MoveUp => new(_haContext, "number.finger_robot_2_move_up");
    ///<summary>S2 Remote Control Switch Indicator value</summary>
    public NumberEntity S2RemoteControlSwitchIndicatorValue => new(_haContext, "number.s2_remote_control_switch_indicator_value");
    ///<summary>Smart RGBTW Bulb Off transition time</summary>
    public NumberEntity SmartRgbtwBulbOffTransitionTime => new(_haContext, "number.smart_rgbtw_bulb_off_transition_time");
    ///<summary>Smart RGBTW Bulb Off transition time</summary>
    public NumberEntity SmartRgbtwBulbOffTransitionTime2 => new(_haContext, "number.smart_rgbtw_bulb_off_transition_time_2");
    ///<summary>Smart RGBTW Bulb On level</summary>
    public NumberEntity SmartRgbtwBulbOnLevel => new(_haContext, "number.smart_rgbtw_bulb_on_level");
    ///<summary>Smart RGBTW Bulb On level</summary>
    public NumberEntity SmartRgbtwBulbOnLevel2 => new(_haContext, "number.smart_rgbtw_bulb_on_level_2");
    ///<summary>Smart RGBTW Bulb On/Off transition time</summary>
    public NumberEntity SmartRgbtwBulbOnOffTransitionTime => new(_haContext, "number.smart_rgbtw_bulb_on_off_transition_time");
    ///<summary>Smart RGBTW Bulb On/Off transition time</summary>
    public NumberEntity SmartRgbtwBulbOnOffTransitionTime2 => new(_haContext, "number.smart_rgbtw_bulb_on_off_transition_time_2");
    ///<summary>Smart RGBTW Bulb On transition time</summary>
    public NumberEntity SmartRgbtwBulbOnTransitionTime => new(_haContext, "number.smart_rgbtw_bulb_on_transition_time");
    ///<summary>Smart RGBTW Bulb On transition time</summary>
    public NumberEntity SmartRgbtwBulbOnTransitionTime2 => new(_haContext, "number.smart_rgbtw_bulb_on_transition_time_2");
    ///<summary>Smart Wi-Fi Lamp Dimmer Off transition time</summary>
    public NumberEntity SmartWiFiLampDimmerOffTransitionTime => new(_haContext, "number.smart_wi_fi_lamp_dimmer_off_transition_time");
    ///<summary>Smart Wi-Fi Lamp Dimmer Off transition time</summary>
    public NumberEntity SmartWiFiLampDimmerOffTransitionTime2 => new(_haContext, "number.smart_wi_fi_lamp_dimmer_off_transition_time_2");
    ///<summary>Smart Wi-Fi Lamp Dimmer On level</summary>
    public NumberEntity SmartWiFiLampDimmerOnLevel => new(_haContext, "number.smart_wi_fi_lamp_dimmer_on_level");
    ///<summary>Smart Wi-Fi Lamp Dimmer On level</summary>
    public NumberEntity SmartWiFiLampDimmerOnLevel2 => new(_haContext, "number.smart_wi_fi_lamp_dimmer_on_level_2");
    ///<summary>Smart Wi-Fi Lamp Dimmer On transition time</summary>
    public NumberEntity SmartWiFiLampDimmerOnTransitionTime => new(_haContext, "number.smart_wi_fi_lamp_dimmer_on_transition_time");
    ///<summary>Smart Wi-Fi Lamp Dimmer On transition time</summary>
    public NumberEntity SmartWiFiLampDimmerOnTransitionTime2 => new(_haContext, "number.smart_wi_fi_lamp_dimmer_on_transition_time_2");
    ///<summary>Tentacle Lamp Smooth off</summary>
    public NumberEntity TapoSmartDimmerSmoothOff => new(_haContext, "number.tapo_smart_dimmer_smooth_off");
    ///<summary>Tentacle Lamp Smooth on</summary>
    public NumberEntity TapoSmartDimmerSmoothOn => new(_haContext, "number.tapo_smart_dimmer_smooth_on");
}