//------------------------------------------------------------------------------
// <auto-generated>
// Generated using NetDaemon CodeGenerator nd-codegen v24.50.0.0
//   At: 2024-12-14T14:51:18.4959074-08:00
//
// *** Make sure the version of the codegen tool and your nugets NetDaemon.* have the same version.***
// You can use following command to keep it up to date with the latest version:
//   dotnet tool update NetDaemon.HassModel.CodeGen
//
// To update this file with latest entities run this command in your project directory:
//   dotnet tool run nd-codegen
//
// In the template projects we provided a convenience powershell script that will update
// the codegen and nugets to latest versions update_all_dependencies.ps1.
//
// For more information: https://netdaemon.xyz/docs/user/hass_model/hass_model_codegen
// For more information about NetDaemon: https://netdaemon.xyz/
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json;
using System.Text.Json.Serialization;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using NetDaemon.HassModel.Entities.Core;

namespace Hammlet.NetDaemon.Models;
public partial class SelectEntities
{
    private readonly IHaContext _haContext;
    public SelectEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all select entities currently registered (at runtime) in Home Assistant as SelectEntity</summary>
    public IEnumerable<SelectEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("select.")).Select(e => new SelectEntity(e));
    ///<summary>Finger Robot 2 Mode</summary>
    public SelectEntity FingerRobot2Mode => new(_haContext, "select.finger_robot_2_mode");
    ///<summary>Smart RGBTW Bulb Power-on behavior on startup</summary>
    public SelectEntity SmartRgbtwBulbPowerOnBehaviorOnStartup => new(_haContext, "select.smart_rgbtw_bulb_power_on_behavior_on_startup");
    ///<summary>Smart RGBTW Bulb Power-on behavior on startup</summary>
    public SelectEntity SmartRgbtwBulbPowerOnBehaviorOnStartup2 => new(_haContext, "select.smart_rgbtw_bulb_power_on_behavior_on_startup_2");
    ///<summary>Smart Wi-Fi Lamp Dimmer Power-on behavior on startup</summary>
    public SelectEntity SmartWiFiLampDimmerPowerOnBehaviorOnStartup => new(_haContext, "select.smart_wi_fi_lamp_dimmer_power_on_behavior_on_startup");
    ///<summary>Smart Wi-Fi Lamp Dimmer Power-on behavior on startup</summary>
    public SelectEntity SmartWiFiLampDimmerPowerOnBehaviorOnStartup2 => new(_haContext, "select.smart_wi_fi_lamp_dimmer_power_on_behavior_on_startup_2");
    ///<summary>Tentacle Lamp Light preset</summary>
    public SelectEntity TapoSmartDimmerLightPreset => new(_haContext, "select.tapo_smart_dimmer_light_preset");
    ///<summary>ytube_music_player Play Mode</summary>
    public SelectEntity YtubeMusicPlayerPlayMode => new(_haContext, "select.ytube_music_player_play_mode");
    ///<summary>ytube_music_player Playlist</summary>
    public SelectEntity YtubeMusicPlayerPlaylist => new(_haContext, "select.ytube_music_player_playlist");
    ///<summary>ytube_music_player Speaker</summary>
    public SelectEntity YtubeMusicPlayerSpeaker => new(_haContext, "select.ytube_music_player_speaker");
}