//------------------------------------------------------------------------------
// <auto-generated>
// Generated using NetDaemon CodeGenerator nd-codegen v24.50.0.0
//   At: 2024-12-14T14:51:18.4976154-08:00
//
// *** Make sure the version of the codegen tool and your nugets NetDaemon.* have the same version.***
// You can use following command to keep it up to date with the latest version:
//   dotnet tool update NetDaemon.HassModel.CodeGen
//
// To update this file with latest entities run this command in your project directory:
//   dotnet tool run nd-codegen
//
// In the template projects we provided a convenience powershell script that will update
// the codegen and nugets to latest versions update_all_dependencies.ps1.
//
// For more information: https://netdaemon.xyz/docs/user/hass_model/hass_model_codegen
// For more information about NetDaemon: https://netdaemon.xyz/
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json;
using System.Text.Json.Serialization;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using NetDaemon.HassModel.Entities.Core;

namespace Hammlet.NetDaemon.Models;
public partial class SensorEntities
{
    private readonly IHaContext _haContext;
    public SensorEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all sensor entities currently registered (at runtime) in Home Assistant as SensorEntity</summary>
    public IEnumerable<SensorEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("sensor.")).Select(e => new SensorEntity(e));
    /// <summary>Enumerates all non-numeric sensor entities currently registered (at runtime) in Home Assistant as SensorEntity</summary>
    public IEnumerable<SensorEntity> EnumerateAllNonNumeric() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("sensor.") && !(e.EntityState?.AttributesJson?.TryGetProperty("unit_of_measurement", out _) ?? false)).Select(e => new SensorEntity(e));
    /// <summary>Enumerates all numeric sensor entities currently registered (at runtime) in Home Assistant as NumericSensorEntity</summary>
    public IEnumerable<NumericSensorEntity> EnumerateAllNumeric() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("sensor.") && (e.EntityState?.AttributesJson?.TryGetProperty("unit_of_measurement", out _) ?? false)).Select(e => new NumericSensorEntity(e));
    ///<summary>800 Series Long Range GPIO Module Status</summary>
    public SensorEntity _800SeriesLongRangeGpioModuleStatus => new(_haContext, "sensor.800_series_long_range_gpio_module_status");
    ///<summary>Briana&apos;s iPhone App Version</summary>
    public SensorEntity BrianaSIphoneAppVersion => new(_haContext, "sensor.briana_s_iphone_app_version");
    ///<summary>Briana&apos;s iPhone Audio Output</summary>
    public SensorEntity BrianaSIphoneAudioOutput => new(_haContext, "sensor.briana_s_iphone_audio_output");
    ///<summary>Briana&apos;s iPhone Battery State</summary>
    public SensorEntity BrianaSIphoneBatteryState => new(_haContext, "sensor.briana_s_iphone_battery_state");
    ///<summary>Briana&apos;s iPhone BSSID</summary>
    public SensorEntity BrianaSIphoneBssid => new(_haContext, "sensor.briana_s_iphone_bssid");
    ///<summary>Briana&apos;s iPhone Connection Type</summary>
    public SensorEntity BrianaSIphoneConnectionType => new(_haContext, "sensor.briana_s_iphone_connection_type");
    ///<summary>Briana&apos;s iPhone Geocoded Location</summary>
    public SensorEntity BrianaSIphoneGeocodedLocation => new(_haContext, "sensor.briana_s_iphone_geocoded_location");
    ///<summary>Briana&apos;s iPhone Last Update Trigger</summary>
    public SensorEntity BrianaSIphoneLastUpdateTrigger => new(_haContext, "sensor.briana_s_iphone_last_update_trigger");
    ///<summary>Briana&apos;s iPhone Location permission</summary>
    public SensorEntity BrianaSIphoneLocationPermission => new(_haContext, "sensor.briana_s_iphone_location_permission");
    ///<summary>Briana&apos;s iPhone SIM 1</summary>
    public SensorEntity BrianaSIphoneSim1 => new(_haContext, "sensor.briana_s_iphone_sim_1");
    ///<summary>Briana&apos;s iPhone SIM 2</summary>
    public SensorEntity BrianaSIphoneSim2 => new(_haContext, "sensor.briana_s_iphone_sim_2");
    ///<summary>Briana&apos;s iPhone SSID</summary>
    public SensorEntity BrianaSIphoneSsid => new(_haContext, "sensor.briana_s_iphone_ssid");
    public SensorEntity CanonSelphyCp1500Http => new(_haContext, "sensor.canon_selphy_cp1500_http");
    ///<summary>IO Series 8/9 D57D Mode</summary>
    public SensorEntity IoSeries89D57dMode => new(_haContext, "sensor.io_series_8_9_d57d_mode");
    ///<summary>IO Series 8/9 D57D Number of sectors</summary>
    public SensorEntity IoSeries89D57dNumberOfSectors => new(_haContext, "sensor.io_series_8_9_d57d_number_of_sectors");
    ///<summary>IO Series 8/9 D57D Pressure</summary>
    public SensorEntity IoSeries89D57dPressure => new(_haContext, "sensor.io_series_8_9_d57d_pressure");
    ///<summary>IO Series 8/9 D57D Sector</summary>
    public SensorEntity IoSeries89D57dSector => new(_haContext, "sensor.io_series_8_9_d57d_sector");
    ///<summary>IO Series 8/9 D57D Toothbrush State</summary>
    public SensorEntity IoSeries89D57dToothbrushState => new(_haContext, "sensor.io_series_8_9_d57d_toothbrush_state");
    ///<summary>Mikaela Battery state</summary>
    public SensorEntity MikaelaBatteryState => new(_haContext, "sensor.mikaela_battery_state");
    ///<summary>Mikaela Charger type</summary>
    public SensorEntity MikaelaChargerType => new(_haContext, "sensor.mikaela_charger_type");
    ///<summary>S2 Remote Control Switch Last seen</summary>
    public SensorEntity Node2LastSeen => new(_haContext, "sensor.node_2_last_seen");
    ///<summary>S2 Remote Control Switch Node status</summary>
    public SensorEntity Node2NodeStatus => new(_haContext, "sensor.node_2_node_status");
    ///<summary>Pixel 8 Battery state</summary>
    public SensorEntity Pixel8BatteryState => new(_haContext, "sensor.pixel_8_battery_state");
    ///<summary>Pixel 8 Charger type</summary>
    public SensorEntity Pixel8ChargerType => new(_haContext, "sensor.pixel_8_charger_type");
    ///<summary>Stuart’s iPhone Activity</summary>
    public SensorEntity StuartsIphoneActivity => new(_haContext, "sensor.stuarts_iphone_activity");
    ///<summary>Stuart’s iPhone Battery State</summary>
    public SensorEntity StuartsIphoneBatteryState => new(_haContext, "sensor.stuarts_iphone_battery_state");
    ///<summary>Stuart’s iPhone BSSID</summary>
    public SensorEntity StuartsIphoneBssid => new(_haContext, "sensor.stuarts_iphone_bssid");
    ///<summary>Stuart’s iPhone Connection Type</summary>
    public SensorEntity StuartsIphoneConnectionType => new(_haContext, "sensor.stuarts_iphone_connection_type");
    ///<summary>Stuart’s iPhone Geocoded Location</summary>
    public SensorEntity StuartsIphoneGeocodedLocation => new(_haContext, "sensor.stuarts_iphone_geocoded_location");
    ///<summary>Stuart’s iPhone Last Update Trigger</summary>
    public SensorEntity StuartsIphoneLastUpdateTrigger => new(_haContext, "sensor.stuarts_iphone_last_update_trigger");
    ///<summary>Stuart’s iPhone SIM 1</summary>
    public SensorEntity StuartsIphoneSim1 => new(_haContext, "sensor.stuarts_iphone_sim_1");
    ///<summary>Stuart’s iPhone SIM 2</summary>
    public SensorEntity StuartsIphoneSim2 => new(_haContext, "sensor.stuarts_iphone_sim_2");
    ///<summary>Stuart’s iPhone SSID</summary>
    public SensorEntity StuartsIphoneSsid => new(_haContext, "sensor.stuarts_iphone_ssid");
    ///<summary>Sun Next dawn</summary>
    public SensorEntity SunNextDawn => new(_haContext, "sensor.sun_next_dawn");
    ///<summary>Sun Next dusk</summary>
    public SensorEntity SunNextDusk => new(_haContext, "sensor.sun_next_dusk");
    ///<summary>Sun Next midnight</summary>
    public SensorEntity SunNextMidnight => new(_haContext, "sensor.sun_next_midnight");
    ///<summary>Sun Next noon</summary>
    public SensorEntity SunNextNoon => new(_haContext, "sensor.sun_next_noon");
    ///<summary>Sun Next rising</summary>
    public SensorEntity SunNextRising => new(_haContext, "sensor.sun_next_rising");
    ///<summary>Sun Next setting</summary>
    public SensorEntity SunNextSetting => new(_haContext, "sensor.sun_next_setting");
    ///<summary>Tentacle Lamp Signal level</summary>
    public SensorEntity TapoSmartDimmerSignalLevel => new(_haContext, "sensor.tapo_smart_dimmer_signal_level");
    ///<summary>wallfire Battery state</summary>
    public SensorEntity WallfireBatteryState => new(_haContext, "sensor.wallfire_battery_state");
    ///<summary>wallfire Charger type</summary>
    public SensorEntity WallfireChargerType => new(_haContext, "sensor.wallfire_charger_type");
    ///<summary>Briana&apos;s iPhone Battery Level</summary>
    public NumericSensorEntity BrianaSIphoneBatteryLevel => new(_haContext, "sensor.briana_s_iphone_battery_level");
    ///<summary>Briana&apos;s iPhone Storage</summary>
    public NumericSensorEntity BrianaSIphoneStorage => new(_haContext, "sensor.briana_s_iphone_storage");
    ///<summary>Color</summary>
    public NumericSensorEntity CanonSelphyCp1500HttpColor => new(_haContext, "sensor.canon_selphy_cp1500_http_color");
    ///<summary>Finger Robot 2 Battery</summary>
    public NumericSensorEntity FingerRobot2Battery => new(_haContext, "sensor.finger_robot_2_battery");
    ///<summary>IO Series 8/9 D57D Battery</summary>
    public NumericSensorEntity IoSeries89D57dBattery => new(_haContext, "sensor.io_series_8_9_d57d_battery");
    ///<summary>IO Series 8/9 D57D Time</summary>
    public NumericSensorEntity IoSeries89D57dTime => new(_haContext, "sensor.io_series_8_9_d57d_time");
    ///<summary>Mikaela Battery level</summary>
    public NumericSensorEntity MikaelaBatteryLevel => new(_haContext, "sensor.mikaela_battery_level");
    ///<summary>Pixel 8 Battery level</summary>
    public NumericSensorEntity Pixel8BatteryLevel => new(_haContext, "sensor.pixel_8_battery_level");
    ///<summary>S2 Remote Control Switch Battery level</summary>
    public NumericSensorEntity S2RemoteControlSwitchBatteryLevel => new(_haContext, "sensor.s2_remote_control_switch_battery_level");
    ///<summary>Song tempo</summary>
    public NumericSensorEntity SpotifyScarletCheckersSongTempo => new(_haContext, "sensor.spotify_scarlet_checkers_song_tempo");
    ///<summary>Stuart’s iPhone Average Active Pace</summary>
    public NumericSensorEntity StuartsIphoneAverageActivePace => new(_haContext, "sensor.stuarts_iphone_average_active_pace");
    ///<summary>Stuart’s iPhone Battery Level</summary>
    public NumericSensorEntity StuartsIphoneBatteryLevel => new(_haContext, "sensor.stuarts_iphone_battery_level");
    ///<summary>Stuart’s iPhone Distance</summary>
    public NumericSensorEntity StuartsIphoneDistance => new(_haContext, "sensor.stuarts_iphone_distance");
    ///<summary>Stuart’s iPhone Floors Ascended</summary>
    public NumericSensorEntity StuartsIphoneFloorsAscended => new(_haContext, "sensor.stuarts_iphone_floors_ascended");
    ///<summary>Stuart’s iPhone Floors Descended</summary>
    public NumericSensorEntity StuartsIphoneFloorsDescended => new(_haContext, "sensor.stuarts_iphone_floors_descended");
    ///<summary>Stuart’s iPhone Steps</summary>
    public NumericSensorEntity StuartsIphoneSteps => new(_haContext, "sensor.stuarts_iphone_steps");
    ///<summary>Stuart’s iPhone Storage</summary>
    public NumericSensorEntity StuartsIphoneStorage => new(_haContext, "sensor.stuarts_iphone_storage");
    ///<summary>wallfire Battery level</summary>
    public NumericSensorEntity WallfireBatteryLevel => new(_haContext, "sensor.wallfire_battery_level");
    ///<summary>Wireless Switch 3241 Battery</summary>
    public NumericSensorEntity WirelessSwitch3241Battery => new(_haContext, "sensor.wireless_switch_3241_battery");
    ///<summary>Wireless Switch 3241 Voltage</summary>
    public NumericSensorEntity WirelessSwitch3241Voltage => new(_haContext, "sensor.wireless_switch_3241_voltage");
    ///<summary>Wireless Switch 6105 Battery</summary>
    public NumericSensorEntity WirelessSwitch6105Battery => new(_haContext, "sensor.wireless_switch_6105_battery");
    ///<summary>Wireless Switch 6105 Voltage</summary>
    public NumericSensorEntity WirelessSwitch6105Voltage => new(_haContext, "sensor.wireless_switch_6105_voltage");
}