//------------------------------------------------------------------------------
// <auto-generated>
// Generated using NetDaemon CodeGenerator nd-codegen v24.50.0.0
//   At: 2024-12-14T14:51:18.5054245-08:00
//
// *** Make sure the version of the codegen tool and your nugets NetDaemon.* have the same version.***
// You can use following command to keep it up to date with the latest version:
//   dotnet tool update NetDaemon.HassModel.CodeGen
//
// To update this file with latest entities run this command in your project directory:
//   dotnet tool run nd-codegen
//
// In the template projects we provided a convenience powershell script that will update
// the codegen and nugets to latest versions update_all_dependencies.ps1.
//
// For more information: https://netdaemon.xyz/docs/user/hass_model/hass_model_codegen
// For more information about NetDaemon: https://netdaemon.xyz/
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json;
using System.Text.Json.Serialization;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using NetDaemon.HassModel.Entities.Core;

namespace Hammlet.NetDaemon.Models;
public partial class SwitchEntities
{
    private readonly IHaContext _haContext;
    public SwitchEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all switch entities currently registered (at runtime) in Home Assistant as SwitchEntity</summary>
    public IEnumerable<SwitchEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("switch.")).Select(e => new SwitchEntity(e));
    ///<summary>Adaptive Lighting Adapt Brightness: AdaptingLighting</summary>
    public SwitchEntity AdaptiveLightingAdaptBrightnessAdaptinglighting => new(_haContext, "switch.adaptive_lighting_adapt_brightness_adaptinglighting");
    ///<summary>Adaptive Lighting Adapt Color: AdaptingLighting</summary>
    public SwitchEntity AdaptiveLightingAdaptColorAdaptinglighting => new(_haContext, "switch.adaptive_lighting_adapt_color_adaptinglighting");
    ///<summary>Adaptive Lighting: AdaptingLighting</summary>
    public SwitchEntity AdaptiveLightingAdaptinglighting => new(_haContext, "switch.adaptive_lighting_adaptinglighting");
    ///<summary>Adaptive Lighting Sleep Mode: AdaptingLighting</summary>
    public SwitchEntity AdaptiveLightingSleepModeAdaptinglighting => new(_haContext, "switch.adaptive_lighting_sleep_mode_adaptinglighting");
    ///<summary>Finger Robot 2 Switch</summary>
    public SwitchEntity FingerRobot2Switch => new(_haContext, "switch.finger_robot_2_switch");
    ///<summary>Hammet BT Proxy BLE Gateway Discovery</summary>
    public SwitchEntity HammetBtProxyBleGatewayDiscovery => new(_haContext, "switch.hammet_bt_proxy_ble_gateway_discovery");
    ///<summary>Hammlet Soundsystem LED</summary>
    public SwitchEntity HammletBedlampLed => new(_haContext, "switch.hammlet_bedlamp_led");
    ///<summary>LG webOS TV EA88 Mute</summary>
    public SwitchEntity LgWebosTvEa88Mute => new(_haContext, "switch.lg_webos_tv_ea88_mute");
    ///<summary>Speakers</summary>
    public SwitchEntity Speakers => new(_haContext, "switch.speakers");
    ///<summary>Tentacle Lamp Auto update enabled</summary>
    public SwitchEntity TapoSmartDimmerAutoUpdateEnabled => new(_haContext, "switch.tapo_smart_dimmer_auto_update_enabled");
    ///<summary>Tentacle Lamp LED</summary>
    public SwitchEntity TapoSmartDimmerLed => new(_haContext, "switch.tapo_smart_dimmer_led");
    ///<summary>Tentacle Lamp</summary>
    public SwitchEntity TentacleLamp => new(_haContext, "switch.tentacle_lamp");
    ///<summary>Tentacle Lamp LED</summary>
    public SwitchEntity TentacleLed => new(_haContext, "switch.tentacle_led");
}