//------------------------------------------------------------------------------
// <auto-generated>
// Generated using NetDaemon CodeGenerator nd-codegen v24.50.0.0
//   At: 2024-12-14T14:51:18.5174582-08:00
//
// *** Make sure the version of the codegen tool and your nugets NetDaemon.* have the same version.***
// You can use following command to keep it up to date with the latest version:
//   dotnet tool update NetDaemon.HassModel.CodeGen
//
// To update this file with latest entities run this command in your project directory:
//   dotnet tool run nd-codegen
//
// In the template projects we provided a convenience powershell script that will update
// the codegen and nugets to latest versions update_all_dependencies.ps1.
//
// For more information: https://netdaemon.xyz/docs/user/hass_model/hass_model_codegen
// For more information about NetDaemon: https://netdaemon.xyz/
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json;
using System.Text.Json.Serialization;
using NetDaemon.HassModel;
using NetDaemon.HassModel.Entities;
using NetDaemon.HassModel.Entities.Core;

namespace Hammlet.NetDaemon.Models;
public partial class UpdateEntities
{
    private readonly IHaContext _haContext;
    public UpdateEntities(IHaContext haContext)
    {
        _haContext = haContext;
    }

    /// <summary>Enumerates all update entities currently registered (at runtime) in Home Assistant as UpdateEntity</summary>
    public IEnumerable<UpdateEntity> EnumerateAll() => _haContext.GetAllEntities().Where(e => e.EntityId.StartsWith("update.")).Select(e => new UpdateEntity(e));
    ///<summary>Adaptive Lighting update</summary>
    public UpdateEntity AdaptiveLightingUpdate => new(_haContext, "update.adaptive_lighting_update");
    ///<summary>Advanced SSH &amp; Web Terminal Update</summary>
    public UpdateEntity AdvancedSshWebTerminalUpdate => new(_haContext, "update.advanced_ssh_web_terminal_update");
    ///<summary>Bubble Card update</summary>
    public UpdateEntity BubbleCardUpdate => new(_haContext, "update.bubble_card_update");
    ///<summary>Bubble update</summary>
    public UpdateEntity BubbleUpdate => new(_haContext, "update.bubble_update");
    ///<summary>button-card update</summary>
    public UpdateEntity ButtonCardUpdate => new(_haContext, "update.button_card_update");
    ///<summary>card-mod update</summary>
    public UpdateEntity CardModUpdate => new(_haContext, "update.card_mod_update");
    ///<summary>Clock Weather Card update</summary>
    public UpdateEntity ClockWeatherCardUpdate => new(_haContext, "update.clock_weather_card_update");
    ///<summary>Collapsable cards update</summary>
    public UpdateEntity CollapsableCardsUpdate => new(_haContext, "update.collapsable_cards_update");
    ///<summary>Config Template Card update</summary>
    public UpdateEntity ConfigTemplateCardUpdate => new(_haContext, "update.config_template_card_update");
    ///<summary>Decluttering Card update</summary>
    public UpdateEntity DeclutteringCardUpdate => new(_haContext, "update.decluttering_card_update");
    ///<summary>Digital Clock update</summary>
    public UpdateEntity DigitalClockUpdate => new(_haContext, "update.digital_clock_update");
    ///<summary>Firmware</summary>
    public UpdateEntity Esp8266DemoLed1Firmware => new(_haContext, "update.esp8266_demo_led_1_firmware");
    ///<summary>ESPHome Device Compiler Update</summary>
    public UpdateEntity EsphomeUpdate => new(_haContext, "update.esphome_update");
    ///<summary>Fan Percent Button Row update</summary>
    public UpdateEntity FanPercentButtonRowUpdate => new(_haContext, "update.fan_percent_button_row_update");
    ///<summary>Filebrowser Update</summary>
    public UpdateEntity FilebrowserUpdate => new(_haContext, "update.filebrowser_update");
    ///<summary>Firemote Card update</summary>
    public UpdateEntity FiremoteCardUpdate => new(_haContext, "update.firemote_card_update");
    ///<summary>fontawesome update</summary>
    public UpdateEntity FontawesomeUpdate => new(_haContext, "update.fontawesome_update");
    ///<summary>HACS update</summary>
    public UpdateEntity HacsUpdate => new(_haContext, "update.hacs_update");
    ///<summary>Firmware</summary>
    public UpdateEntity HammetBtProxyFirmware => new(_haContext, "update.hammet_bt_proxy_firmware");
    ///<summary>Firmware</summary>
    public UpdateEntity HammletMusicWledFirmware => new(_haContext, "update.hammlet_music_wled_firmware");
    ///<summary>HiFiBerry update</summary>
    public UpdateEntity HifiberryUpdate => new(_haContext, "update.hifiberry_update");
    ///<summary>Home Assistant Core Update</summary>
    public UpdateEntity HomeAssistantCoreUpdate => new(_haContext, "update.home_assistant_core_update");
    ///<summary>Home Assistant Operating System Update</summary>
    public UpdateEntity HomeAssistantOperatingSystemUpdate => new(_haContext, "update.home_assistant_operating_system_update");
    ///<summary>Home Assistant Supervisor Update</summary>
    public UpdateEntity HomeAssistantSupervisorUpdate => new(_haContext, "update.home_assistant_supervisor_update");
    ///<summary>Hourly Weather Card update</summary>
    public UpdateEntity HourlyWeatherCardUpdate => new(_haContext, "update.hourly_weather_card_update");
    ///<summary>iOS Themes - Dark Mode and Light Mode update</summary>
    public UpdateEntity IosThemesDarkModeAndLightModeUpdate => new(_haContext, "update.ios_themes_dark_mode_and_light_mode_update");
    ///<summary>Kiosk Mode update</summary>
    public UpdateEntity KioskModeUpdate => new(_haContext, "update.kiosk_mode_update");
    ///<summary>layout-card update</summary>
    public UpdateEntity LayoutCardUpdate => new(_haContext, "update.layout_card_update");
    ///<summary>LG WebOS Remote Control update</summary>
    public UpdateEntity LgWebosRemoteControlUpdate => new(_haContext, "update.lg_webos_remote_control_update");
    ///<summary>Light Entity Card update</summary>
    public UpdateEntity LightEntityCardUpdate => new(_haContext, "update.light_entity_card_update");
    ///<summary>Material Rounded Theme - Based on Material You by Google on Android update</summary>
    public UpdateEntity MaterialRoundedThemeBasedOnMaterialYouByGoogleOnAndroidUpdate => new(_haContext, "update.material_rounded_theme_based_on_material_you_by_google_on_android_update");
    ///<summary>Matter Server Update</summary>
    public UpdateEntity MatterServerUpdate => new(_haContext, "update.matter_server_update");
    ///<summary>Mini Media Player update</summary>
    public UpdateEntity MiniMediaPlayerUpdate => new(_haContext, "update.mini_media_player_update");
    ///<summary>Mosquitto broker Update</summary>
    public UpdateEntity MosquittoBrokerUpdate => new(_haContext, "update.mosquitto_broker_update");
    ///<summary>Mushroom Themes update</summary>
    public UpdateEntity MushroomThemesUpdate => new(_haContext, "update.mushroom_themes_update");
    ///<summary>Mushroom update</summary>
    public UpdateEntity MushroomUpdate => new(_haContext, "update.mushroom_update");
    ///<summary>NetDaemon update</summary>
    public UpdateEntity NetdaemonUpdate => new(_haContext, "update.netdaemon_update");
    ///<summary>NetDaemon V5 (.NET 9) Update</summary>
    public UpdateEntity NetdaemonV5Net9Update => new(_haContext, "update.netdaemon_v5_net_9_update");
    ///<summary>Node-RED Update</summary>
    public UpdateEntity NodeRedUpdate => new(_haContext, "update.node_red_update");
    ///<summary>O365 Card update</summary>
    public UpdateEntity O365CardUpdate => new(_haContext, "update.o365_card_update");
    ///<summary>Office 365 update</summary>
    public UpdateEntity Office365Update => new(_haContext, "update.office_365_update");
    ///<summary>Pirate Weather update</summary>
    public UpdateEntity PirateWeatherUpdate => new(_haContext, "update.pirate_weather_update");
    ///<summary>PoLR YTube Media Card update</summary>
    public UpdateEntity PolrYtubeMediaCardUpdate => new(_haContext, "update.polr_ytube_media_card_update");
    ///<summary>Portainer Update</summary>
    public UpdateEntity PortainerUpdate => new(_haContext, "update.portainer_update");
    ///<summary>Portainer update</summary>
    public UpdateEntity PortainerUpdate2 => new(_haContext, "update.portainer_update_2");
    ///<summary>S2 Remote Control Switch Firmware</summary>
    public UpdateEntity S2RemoteControlSwitchFirmware => new(_haContext, "update.s2_remote_control_switch_firmware");
    ///<summary>Samba NAS Update</summary>
    public UpdateEntity SambaNasUpdate => new(_haContext, "update.samba_nas_update");
    ///<summary>Samba share Update</summary>
    public UpdateEntity SambaShareUpdate => new(_haContext, "update.samba_share_update");
    ///<summary>Seafile Update</summary>
    public UpdateEntity SeafileUpdate => new(_haContext, "update.seafile_update");
    ///<summary>Select list Card update</summary>
    public UpdateEntity SelectListCardUpdate => new(_haContext, "update.select_list_card_update");
    ///<summary>slider-entity-row update</summary>
    public UpdateEntity SliderEntityRowUpdate => new(_haContext, "update.slider_entity_row_update");
    ///<summary>Smart RGBTW Bulb</summary>
    public UpdateEntity SmartRgbtwBulb => new(_haContext, "update.smart_rgbtw_bulb");
    ///<summary>Smart RGBTW Bulb</summary>
    public UpdateEntity SmartRgbtwBulb2 => new(_haContext, "update.smart_rgbtw_bulb_2");
    ///<summary>Smart Wi-Fi Lamp Dimmer</summary>
    public UpdateEntity SmartWiFiLampDimmer => new(_haContext, "update.smart_wi_fi_lamp_dimmer");
    ///<summary>Smart Wi-Fi Lamp Dimmer</summary>
    public UpdateEntity SmartWiFiLampDimmer2 => new(_haContext, "update.smart_wi_fi_lamp_dimmer_2");
    ///<summary>Sonoff LAN update</summary>
    public UpdateEntity SonoffLanUpdate => new(_haContext, "update.sonoff_lan_update");
    ///<summary>Studio Code Server Update</summary>
    public UpdateEntity StudioCodeServerUpdate => new(_haContext, "update.studio_code_server_update");
    ///<summary>youtube update</summary>
    public UpdateEntity YoutubeUpdate => new(_haContext, "update.youtube_update");
    ///<summary>ytube_music_player update</summary>
    public UpdateEntity YtubeMusicPlayerUpdate => new(_haContext, "update.ytube_music_player_update");
    ///<summary>Z-Wave JS UI Update</summary>
    public UpdateEntity ZWaveJsUiUpdate => new(_haContext, "update.z_wave_js_ui_update");
}